/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./components/crud/add.vue')['default']
    Breadcrumb: typeof import('./components/functional/breadcrumb.vue')['default']
    Browse: typeof import('./components/crud/fields/browse.vue')['default']
    Cell_item: typeof import('./components/custom/cell_item.vue')['default']
    CellItem: typeof import('./components/custom/CellItem.vue')['default']
    Chat: typeof import('./components/functional/chat/chat.vue')['default']
    ChatContact: typeof import('./components/functional/chat/chat-contact.vue')['default']
    Checkbox: typeof import('./components/crud/fields/checkbox.vue')['default']
    CloseButton: typeof import('./components/functional/close-button.vue')['default']
    CollectionEditor: typeof import('./components/CollectionEditor.vue')['default']
    CollectionEditorOption: typeof import('./components/CollectionEditorOption.vue')['default']
    Custom: typeof import('./components/custom.vue')['default']
    CustomList: typeof import('./components/custom/CustomList.vue')['default']
    CustomListItem: typeof import('./components/custom/custom-list-item.vue')['default']
    Delete: typeof import('./components/crud/delete.vue')['default']
    Drawer: typeof import('./components/functional/drawer.vue')['default']
    Dropdown: typeof import('./components/crud/fields/dropdown.vue')['default']
    Edit: typeof import('./components/crud/edit.vue')['default']
    EditIcon: typeof import('./components/functional/icons/EditIcon.vue')['default']
    Form: typeof import('./components/crud/form.vue')['default']
    Grid: typeof import('./components/functional/grid/Grid.vue')['default']
    Header: typeof import('./components/functional/chat/partials/header.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LinkButton: typeof import('./components/functional/buttons/LinkButton.vue')['default']
    List: typeof import('./components/crud/list.vue')['default']
    ListItem: typeof import('./components/crud/list-item.vue')['default']
    PageComponent: typeof import('./components/page/PageComponent.vue')['default']
    PageComponentContainer: typeof import('./components/page/PageComponentContainer.vue')['default']
    PageEditor: typeof import('./components/page/PageEditor.vue')['default']
    Pagination: typeof import('./components/crud/pagination.vue')['default']
    PrimaryButton: typeof import('./components/functional/buttons/PrimaryButton.vue')['default']
    Radio: typeof import('./components/crud/fields/radio.vue')['default']
    RoundedPlus: typeof import('./components/icons/RoundedPlus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./components/crud/fields/select.vue')['default']
    SitePageTree: typeof import('./components/SitePageTree.vue')['default']
    Spinner: typeof import('./components/functional/spinner.vue')['default']
    SvgFlag: typeof import('./components/functional/svg-icons/svg-flag.vue')['default']
    SvgIcon: typeof import('./components/functional/svg-icons/svg-icon.vue')['default']
    Text: typeof import('./components/crud/fields/text.vue')['default']
    TextArea: typeof import('./components/crud/fields/text-area.vue')['default']
    Zoomer: typeof import('./components/Zoomer.vue')['default']
  }
}
